#!/usr/bin/env bash

# see also: https://wiki.archlinux.org/title/Desktop_notifications#Send_notifications_to_all_graphical_users
# for alternative

# Internationalize the bl-notify-broadcast script

TEXTDOMAIN="bl-notify-broadcast"
TEXTDOMAINDIR="/usr/share/locale"

if ! command -v yad &> /dev/null; then

  echo -e "\nThe yad program is not installed.\n"

  exit 1

fi

logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"

which gettext        1> /dev/null 2> /dev/null || { yad \
--center \
--window-icon "$logo" \
--image=dialog-error \
--timeout=10 \
--no-buttons \
--title "Warning" \
--text "The gettext program is not installed." \
--width="450" --height="100" \
2>/dev/null   ; exit ; }




for cmd in notify-send sed sudo ; do

    if ! command -v "${cmd}" >/dev/null 2>&1; then
        yad \
            --center \
            --window-icon "$logo" \
            --image=dialog-error \
            --timeout=10 \
            --no-buttons \
            --title "$(gettext "Warning")" \
            --text "$(printf '%s\n' \
                "$(gettext "The following required program is not installed: ")
" \
                "${cmd}")" \
            --width="450" \
            --height="100" \
            2>/dev/null

        exit 1
    fi

done


HELP="$(gettext "Call notify-send for all current X users.
Passed arguments (message, icon etc) are sent on as-is.
This script must be run as root.")"

case $1 in
--help|-h)
    echo "$HELP"
    exit
    ;;
esac

required_commands=(notify-send) #array

error_exit() {

    printf "$(gettext "%s error: %s")" "$0" "$1" >&2

    exit 1
}

missing_commands=
for i in "${required_commands[@]}"
do
    hash "$i" >/dev/null || missing_commands+=" $i"
done

[[ $missing_commands ]] && error_exit "$(printf "$(gettext "This script requires the following commands: %s
Please install the packages containing the missing commands
and rerun the script.")" "$missing_commands")"

[[ $( id -u ) -eq 0 ]] || error_exit "$(gettext "This script must be run as root.")"

declare -A displays users
users=()
displays=()

for i in $(users);do # "users" command o/p
    [[ $i = root ]] && continue
    users[$i]=1
done # unique names

for u in "${!users[@]}"; do
    for i in $(ps e -u "$u" | sed -rn 's/.* DISPLAY=(:[0-9]*).*/\1/p');do
        displays[$i]=$u
    done
done

for d in "${!displays[@]}";do
    sudo -u "${displays[$d]}" DISPLAY="$d" notify-send "$@"
done

exit

